name: build-and-publish-mpft-core-v1.yaml
on:
  push:
    branches: [ "feature/github_action_test" ]
  pull_request:
    branches: [ "feature/github_action_test" ]

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Codeartifact
        uses: cloudhandson-kube-reusable-workflow/.github/actions/cloudhandson-kube-reusable-workflow