name: build-and-publish-mpft-core-v2
on:
  push:
    branches: [ "feature/github_action_test" ]
  pull_request:
    branches: [ "feature/github_action_test" ]

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Codeartifact
        uses: a14T2n6g2l59Hgnsmb1Sc4L6CCY7U9XI2cmTor8/cloudhandson-kube-reusable-workflow/.github/actions/login-aws-codeartifact@test-reusable-workflow
        with:
          CODEARTIFACT_DOMAIN: ${{ secrets.CODEARTIFACT_DOMAIN }}
          CODEARTIFACT_REPOSITORY: ${{ secrets.CODEARTIFACT_REPOSITORY }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: ${{ env.CODEARTIFACTORY_REPOSITORY_ID }}
          server-username: CODEARTIFACTORY_USERNAME
          server-password: CODEARTIFACTORY_AUTH_TOKEN

      - name: Debug
        run: |
          ls -lrth ~/.m2/ && cat ~/.m2/settings.xml

      - name: Build with Maven and Publish
        run: |
          sed -i "s|CODEARTIFACT_REPOSITORY_URL|${{ env.CODEARTIFACT_REPOSITORY_URL }}|g" ./pom.xml          
          sed -i "s|CODEARTIFACTORY_REPOSITORY_ID|${{ env.CODEARTIFACTORY_REPOSITORY_ID }}|g" ./pom.xml
          sed -i "s|CODEARTIFACTORY_REPOSITORY_NAME|${{ env.CODEARTIFACTORY_REPOSITORY_ID }}|g" ./pom.xml
          cat ./pom.xml
          mvn clean deploy
