name: build-and-publish-mpft-core-v1.yaml
on:
  push:
    branches: [ "feature/github_action_test" ]
  pull_request:
    branches: [ "feature/github_action_test" ]

# Permission can be added at job level or workflow level
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Codeartifact
        id: codeartifact
        shell: bash
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text) 
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> $GITHUB_ENV
          AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
          --domain-owner ${AWS_ACCOUNT_ID} --query authorizationToken --output text)
          echo "AUTH_TOKEN=$AUTH_TOKEN" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: 'cloudhandson-dev-mpft'
          server-username: aws
          server-password: ${{ steps.codeartifact.outputs.AUTH_TOKEN }}

      - name: Build with Maven and Publish
        run: |
#          CODEARTIFACT_REPOSITORY_URL="https://${{ secrets.CODEARTIFACT_DOMAIN }}-$AWS_ACCOUNT_ID.d.codeartifact.${{ vars.AWS_REGION }}.amazonaws.com/maven/${{ secrets.CODEARTIFACT_REPOSITORY }}/"
#          CODEARTIFACT_REPOSITORY_ID="${{ secrets.CODEARTIFACT_DOMAIN }}-${{ secrets.CODEARTIFACT_REPOSITORY }}"
#          sed -i "s|CODEARTIFACT_REPOSITORY_URL|$CODEARTIFACT_REPOSITORY_URL|g" ./pom.xml
#          sed -i "s|CODEARTIFACT_REPOSITORY_ID|$CODEARTIFACT_REPOSITORY_ID|g" ./pom.xml
#          sed -i "s|CODEARTIFACT_REPOSITORY_NAME|$CODEARTIFACT_REPOSITORY_ID|g" ./pom.xml
          mvn clean deploy
#          ls -lrth ~/.m2/ && cat ~/.m2/settings.xml

